language: node_js
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
node_js:
- '0.10'
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAJH2D5IPIRHYJT5IA
  - DOCKER_USERNAME=octoblu
  - DEPLOY_APPLICATION_NAME=tentacle-server
  - DEPLOY_REGION=us-west-2
  - DEPLOY_BUCKET=octoblu-deploy
  - DEPLOYMENT_GROUP=master
  - DEPLOY_KEY=tentacle-server/tentacle-server-$TRAVIS_COMMIT.zip
  - secure: Qhg5iELNIpei/XESmZYP4ZpmY48Xt68oGnMTQFOoVmJKTXpzsGAlQCzDVPo5D1WOelinUQauNSDSTBtT5072WOumUc8fTpYFtBd5UWElVkELpQls4iuaJq1zVyFMpThUEnU9bJytR8qkbalbvUY2e++MssVDMvPiB487vhVC2YuYOhphgLn9EAv89EpTtq+675Caxqk7xT59VREUOHaac/LSMnv9N7hAxvx03hlvftfMAGmQw/zVzZvVNIepHsg4+9nZl3+l6JB5Fhp7GpargTkHJVo7Cmo3qJboo9oqylLcUZnLdCGnTgM+4vLylL8QKmRS+MpCRHs/YHeNUpgfit7nbF4NP3lsBzHbYUH8xtWdiql15aWjKJMHPK1m7C0nr2x3eCVyP13J6nMOgXGY34rTpwvLaF0vjmOwA/bwYscTOMzTQ5mj/xVwS3wikPe0ywuLuaWJ/Eo/dToyrjeT3IOlWG27dutQUP9Z6TY+BuJZj8kGTv+9g8M0ra0K0sQuqixAaspRmHAEi5HpwmUuquPxqxZOy/PxNNDlIHoFl99fK6S51EAN9Hkz5z00cPp7LVOHn334gQbwBqcQr1w0gJi0JEHRn/bx9EtA5joDtR4e/g0Zf6Cz8q0aaH+HfHPk+8eIY9p5tx9QzYEvFlwurG+YpOB93takOuBeQLQkmsc=
  - secure: cIskEufY6TpsO6zWAriFHGO+rNXzx7jcKPYFIf0knXRLK4AJtV+CY2P7E1NGU7x0r2lhO4NgRtUDJ0UUHtn3fYDyrklUYzZFLnlofGlK9czmb1npREs8o9DDB95R/GufR6sRshZvMTiyQm8LnT+Nf3NFyxuRw+6KsP4UZkMhYNMIfzfG1luk4ByvxVUhkck7QaHDnDqSZ53Eey6YbSaxAuYs8UjLqbxhJpS1pc8WYWcbecDNq8flobi7j9YkvR8TLbiMTlhtyj/4VoVhmNXCJUzqE1YHROYuTAFfiS64X+6vDxZfCacg7+cgNSl2Klgx1iUFxj/g1zHKY2SAsyazhM9njFDsiyd3xz+Xw94IbrUfTH1MchW0gqq/X0FucKc5hDFNP50yrnsp6+s/gZzkinOwwQ7OFMLwx7dvdTkoOuwr/1NBy51J55331EDnjucFUuSixILouz1H394rq3UrGSHHm9NrHk0kTam/9gk99GfOXiTUaVd6Vf1IWku4siasPGVrXlVgM6P/p6cesvrhSpHdDidZoj77bWJOdnaSPefFyDB0s7r7LldiFalgMhoBmIn7S+fKtvDlBSutT1Umm8h0yT3O+onOa5pQWJ9Rw9nvMEbFMcUadnVfGaJ9FIELPLkyTW5elPjSMPO36qt5+zB9HG6Sdnrtcgb3e0G0FT4=
after_success:
- .kubernetes/travis_after_success
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key: &1
    secure: SW6Hp0h+CPX9J/6klyNzFv9nu5cO52KZ7Onc9ZdlcDoaZcfijrkcaT8JPEb9YB/GU9/z0GPthi90p23/EuCnvk/GYI0YNO9XdJdpcNsEEfCP/Kp1P44lq9sM+dBpzTNUbliVbsgpq1HhXOStJ0qASs0umQLVqXhbFyeN4IhBwTpzq87KaGsk7tHZPQb8Cx4lI+QC6EGOh7+m6kjskO8VRXYmjWFLnl9E/zRL+C9WM0b057xqm6Tv73wkTYk99YuWE35f7UOwQvthDi6B4i4d31jySDUXYXoy08uhcTGcN/6dH0lRqvnGdpHxJZjfRy4fig9VT5aYRX0+6A/7RuMC3/zvBhFmyljBzkLItB3Pt21bSGTVAb8tcUa3srj3C6JCE4ks6VPhRd8xRSkx/clrkDIs5rnq5KGWK0V4b5iDPxwfqzqyQZe0AXAn67Al33bkLJbkSl+Z+CgsZnreNCbNOhq1xT7PzHhOgANFnEZBdVHvgTedYCQIlOSSKekaYgIq7jIuYriS5d8ZcJqpHMmu/5MkHjsgjYJdcpgkAL4lB921KnCjCq60aE+bzLTFSPX3JFpJ8hOUcFyIYdAfp5HR9Iu0OEwLGpONZj/SxBChBHpBhd0Rtbg04OjngMvbUbGDKPDHzCQJCo8GITqC3txsHZtKIApRl/aH/XIAdk2YkSg=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  bucket: octoblu-deploy
  on:
    branch: master
- provider: codedeploy
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key: *1
  bucket: octoblu-deploy
  key: docker-builder/tentacle-server-$TRAVIS_COMMIT.zip
  bundle_type: zip
  region: us-west-2
  application: docker-builder
  deployment_group: tentacle-server
  on:
    branch: master
