language: node_js
sudo: false
cache:
  bundler: true
  directories:
  - node_modules
node_js:
- '0.10'
env:
  global:
  - AWS_ACCESS_KEY_ID=AKIAJH2D5IPIRHYJT5IA
  - DOCKER_USERNAME=octoblu
  - DEPLOY_APPLICATION_NAME=tentacle-server
  - DEPLOY_REGION=us-west-2
  - DEPLOY_BUCKET=octoblu-deploy
  - DEPLOYMENT_GROUP=master
  - DEPLOY_KEY=tentacle-server/tentacle-server-$TRAVIS_COMMIT.zip
after_success:
- .kubernetes/travis_after_success
deploy:
- provider: s3
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key: &1
    secure: 
  local_dir: dpl_cd_upload
  skip_cleanup: true
  bucket: octoblu-deploy
  on:
    branch: master
- provider: codedeploy
  access_key_id: AKIAJH2D5IPIRHYJT5IA
  secret_access_key: *1
  bucket: octoblu-deploy
  key: docker-builder/tentacle-server-$TRAVIS_COMMIT.zip
  bundle_type: zip
  region: us-west-2
  application: docker-builder
  deployment_group: tentacle-server
  on:
    branch: master
